# Generated by Django 3.0.4 on 2020-04-23 12:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200423_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
