# Generated by Django 3.0.4 on 2020-04-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200423_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='test', verbose_name='content'),
            preserve_default=False,
        ),
    ]
